select EMPLOYEE.NAME, EMPLOYEE.ADDRESS, DEPARTAMENT.NAME FROM EMPLOYEE
LEFT JOIN DEPARTAMENT on EMPLOYEE.DEPARTAMENT_ID = DEPARTAMENT.ID;

select EMPLOYEE.NAME, EMPLOYEE.ADDRESS, DEPARTAMENT.NAME FROM EMPLOYEE
RIGHT JOIN DEPARTAMENT on EMPLOYEE.DEPARTAMENT_ID = DEPARTAMENT.ID;